### ISSUE TITLE
求支持下 Goland

### ISSUE THREAD

**Issue by Allenxuxu** [JoysKang/QuickOpen#1]

**Comment by JoysKang** [comment]
![image](https://user-images.githubusercontent.com/11786681/115492246-048ad900-a294-11eb-8370-b6fd63481947.png)
本身就支持啊   你那使用是有什么问题吗？

**Comment by Allenxuxu** [comment]
安装之后需要配置啥吗，我现在啥搜索不到

**Comment by JoysKang** [comment]
![image](https://user-images.githubusercontent.com/11786681/115492524-81b64e00-a294-11eb-9674-c271d9081ebb.png)
zhe'li
这里有历史记录吗？

**Comment by Allenxuxu** [comment]
和我的版本有关吗，我是 GoLand 2021.1。 
这里实现的原理是去 Goland 的配置文件吗？如果是，我可以去检查下

**Comment by JoysKang** [comment]
是的  也许新版本配置改了

**Comment by Allenxuxu** [comment]
是读取的哪个文件，我找找看

**Comment by JoysKang** [comment]
![image](https://user-images.githubusercontent.com/11786681/115493265-ff2e8e00-a295-11eb-9860-3371e91ab16d.png)
ssorry  本地开发忘记修改了   今天会再发一版 修正这个错误

**Comment by JoysKang** [comment]
已修复
