### ISSUE TITLE
关于m1 Mac无法打开项目的问题

### ISSUE THREAD

**Issue by leqq00** [JoysKang/QuickOpen#2]
![image](https://user-images.githubusercontent.com/35185509/123575162-c1089a00-d803-11eb-9826-22e71a5ffccc.png)

**Comment by leqq00** [comment]
我在我的电脑尝试了好几个这种软件都不行，我的是2021.1的版本

**Comment by leqq00** [comment]
在论坛里面好像和我一样的问题有很多人

**Comment by JoysKang** [comment]
可以看下 phpstorm 在M1里边的可执行文件路径是不是 /Applications/PhpStorm.app/Contents/MacOS/phpstorm 我这没有M1的机器

**Comment by JoysKang** [comment]
长时间为回复  暂时关闭
