### ISSUE TITLE
不知道是不是打开方式有误一直没有成功搜出任何历史

### ISSUE THREAD

**Issue by zealforbeing** [JoysKang/QuickOpen#4]
已经解压 readXcode.zip 到 ~/Library/Application Support/uTools/plugins 文件夹下，不管搜索框上输入什么都搜索不出来，正确是否是 History projectName?

**Comment by JoysKang** [comment]
先输入 History 回车 然后输入项目名称，或者是直接输入 :xcode 会显示所有 xcode 的历史记录

**Comment by JoysKang** [comment]
今天会发布一个不需要 二进制文件的版本

**Comment by JoysKang** [comment]
今天会发布一个不需要 二进制文件的版本

**Comment by JoysKang** [comment]
utools 的大佬休假去了，得晚晚。 不想等的话用我打好的包
[QuickOpen-1.0.1.upx.zip](https://github.com/JoysKang/QuickOpen/files/7194286/QuickOpen-1.0.1.upx.zip)

**Comment by zealforbeing** [comment]
> utools 的大佬休假去了，得晚晚。 不想等的话用我打好的包
> [QuickOpen-1.0.1.upx.zip](https://github.com/JoysKang/QuickOpen/files/7194286/QuickOpen-1.0.1.upx.zip)

大佬，安装了你这个包还是搜不出东西来，不管是输入 History 还是 :xcode ,还需要设置什么隐私权限吗？我这边的环境是 big sur 11.5.2 utools v 2.1.0

**Comment by JoysKang** [comment]
/Users/xxx/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.apple.dt.xcode.sfl2

你看下上边的文件是否存在  xxx改成你的用户名

**Comment by zealforbeing** [comment]
> /Users/xxx/Library/Application\ Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.apple.dt.xcode.sfl2
> 
> 你看下上边的文件是否存在 xxx改成你的用户名

存在的，另外一个插件 我的项目 能搜出历史来

**Comment by JoysKang** [comment]
方便把你的文件提供出来吗   我尝试下   今天新发布了一版  不使用二进制文件已经可以读取xcode了   我的项目 作者我知道 这一版就是他给的建议

**Comment by JoysKang** [comment]
怀疑是部分不存在导致大搜索错误，https://github.com/JoysKang/QuickOpen/issues/5 包含了部分描述   暂时关闭该 issue  如果还有问题可以再打开
