### ISSUE TITLE
Goland 里已删除的的 recent project 还是会出现在插件的结果集里

### ISSUE THREAD

**Issue by Allenxuxu** [JoysKang/QuickOpen#5]

**Comment by Allenxuxu** [comment]
很好奇这里的原理，我去代码里的这个目录，似乎是没有的啊，那是怎么查到我的 recent project 的啊🤔
![image](https://user-images.githubusercontent.com/20566897/141098686-51677d25-ed7d-4392-bcd1-32efc0af7f8d.png)

**Comment by JoysKang** [comment]
清除 recent project 后需要关闭编辑器，Goland 才会将删除的从 recentProjects.xml 删除 recent project ，之后就搜不到了

原理是读取 recentProjects.xml，位置在 `/Users/xxx/Library/Application\ Support/JetBrains/GoLand2021.2/options/recentProjects.xml`

**Comment by Allenxuxu** [comment]
我已经关闭过 Goland 了。

这个目录下 /Users/xxx/Library/Application\ Support/JetBrains/ ，我有多个 Goland 版本：GoLand2021.3 GoLand2021.2  GoLand2020.2 等，应该是我升级导致的，插件会取最新的版本吗, 看起来她似乎取了所有的目录做了一次 merge ？ 
这应该是导致这个现象的原因，我升级后，原来的版本目录还在，里面的 recentProjects.xml goland 没有做清除。
@JoysKang

**Comment by Allenxuxu** [comment]
> 我已经关闭过 Goland 了。
> 
> 这个目录下 /Users/xxx/Library/Application\ Support/JetBrains/ ，我有多个 Goland 版本：GoLand2021.3 GoLand2021.2 GoLand2020.2 等，应该是我升级导致的，插件会取最新的版本吗, 看起来她似乎取了所有的目录做了一次 merge ？ 这应该是导致这个现象的原因，我升级后，原来的版本目录还在，里面的 recentProjects.xml goland 没有做清除。 @JoysKang

这里感觉插件应该取一个最大版本读取，而不是读取所有版本里的 recentProject.xml 做merge 。

**Comment by JoysKang** [comment]
是的   测试了下  确实存在这样的问题   需要修正下

> 我已经关闭过 Goland 了。
> 
> 这个目录下 /Users/xxx/Library/Application\ Support/JetBrains/ ，我有多个 Goland 版本：GoLand2021.3 GoLand2021.2 GoLand2020.2 等，应该是我升级导致的，插件会取最新的版本吗, 看起来她似乎取了所有的目录做了一次 merge ？ 这应该是导致这个现象的原因，我升级后，原来的版本目录还在，里面的 recentProjects.xml goland 没有做清除。 @JoysKang

**Comment by Allenxuxu** [comment]
1.0.3 似乎有问题，我升级后，什么都搜不到了

**Comment by Allenxuxu** [comment]
> 1.0.3 似乎有问题，我升级后，什么都搜不到了

可以先回滚版本吗😅

**Comment by JoysKang** [comment]
你是不是存在降级的操作？  如果存在  去/Users/xxx/Library/Application\ Support/JetBrains/ 把最新版的文件夹删了就好

**Comment by Allenxuxu** [comment]
> 你是不是存在降级的操作？ 如果存在 去/Users/xxx/Library/Application\ Support/JetBrains/ 把最新版的文件夹删了就好

我没有降级，但是之前我把旧版本的 recentProject.xml 改名了recentProject.xml-bak ，让之前的版本搜不到

**Comment by JoysKang** [comment]
![image](https://user-images.githubusercontent.com/11786681/141744404-8e06ee40-0587-4fbc-8d6b-d9a9659c7b07.png)
偷懒  使用的是字符串排序  但是 -bak 并不会影响到搜索

**Comment by JoysKang** [comment]
您还有其他地方的修改吗？

**Comment by Allenxuxu** [comment]
```
➜  JetBrains ls
GoLand2020.2       GoLand2020.3       GoLand2021.1       GoLand2021.2       Goland             IntelliJIdea2021.1 IntelliJIdea2021.2 PyCharm2020.2      Pycharm            bl                 consentOptions     crl
```

没有改其他的，上面是我的目录

**Comment by JoysKang** [comment]
如果着急使用就先删除历史版本的目录吧   后边我会修正下  以最新修改的文件为去重标的   只读最近使用的

**Comment by JoysKang** [comment]
> ```
> ➜  JetBrains ls
> GoLand2020.2       GoLand2020.3       GoLand2021.1       GoLand2021.2       Goland             IntelliJIdea2021.1 IntelliJIdea2021.2 PyCharm2020.2      Pycharm            bl                 consentOptions     crl
> ```
> 
> 没有改其他的，上面是我的目录

模拟你的目录  没有复现

**Comment by Allenxuxu** [comment]
> > ```
> > ➜  JetBrains ls
> > GoLand2020.2       GoLand2020.3       GoLand2021.1       GoLand2021.2       Goland             IntelliJIdea2021.1 IntelliJIdea2021.2 PyCharm2020.2      Pycharm            bl                 consentOptions     crl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 没有改其他的，上面是我的目录
> 
> 模拟你的目录 没有复现

我感觉是不是哪里报错了，因为出了 goland ，其他ide的也一个都搜不出来了，感觉是哪里报错中止了？

**Comment by JoysKang** [comment]
肯定是哪报错了  但是我这没模拟出来

**Comment by Allenxuxu** [comment]
> 肯定是哪报错了 但是我这没模拟出来

我想下载一个 `uTools 开发者工具` 自己试试的，官网没找到下载地址😅

**Comment by JoysKang** [comment]
![image](https://user-images.githubusercontent.com/11786681/141753807-e271f55e-709f-4185-b422-a82b82a49dc9.png)

**Comment by Allenxuxu** [comment]
啊这，我以为是一个单独应用呢，我来试试看

**Comment by Allenxuxu** [comment]
![image](https://user-images.githubusercontent.com/20566897/141758293-65d17f57-1c9f-4e61-aa61-50eeff77d109.png)

**Comment by JoysKang** [comment]
你需要使用 utools 运行测试   如果想直接node xxx.js 运行 参考图中的注释
![image](https://user-images.githubusercontent.com/11786681/141758732-1c632cff-ff64-4351-8738-512f2cb03643.png)

**Comment by Allenxuxu** [comment]
> 你需要使用 utools 运行测试 如果想直接node xxx.js 运行 参考图中的注释 ![image](https://user-images.githubusercontent.com/11786681/141758732-1c632cff-ff64-4351-8738-512f2cb03643.png)

js 我不是非常了解哈，我没有使用 node 运行它，我就是按照 utools 的方法在 utools 里运行的

**Comment by JoysKang** [comment]
npm install了吗

**Comment by Allenxuxu** [comment]
> npm install了吗

😅，可以了，utools 有办法看日志吗？

**Comment by JoysKang** [comment]
没  只能console

> > npm install了吗
> 
> 😅，可以了，utools 有办法看日志吗？

**Comment by Allenxuxu** [comment]
ReferenceError: utools is not defined
    at Object.readXcodeHistory (/Users/xxxx/code/QuickOpen/src/readXcodeHistory.js:41:26)
    at Object.xcodeParsers (/Users/xxxx/code/QuickOpen/src/parsers.js:150:24)
    at getFileContent (/Users/xxx/code/QuickOpen/src/preload.js:81:24)
    at Object.next (/Users/xxxx/code/QuickOpen/src/preload.js:114:32)
    at getHistory (/Users/xxx/code/QuickOpen/src/preload.js:153:16)
    at async /Users/xxx/code/QuickOpen/src/preload.js:231:5

**Comment by Allenxuxu** [comment]
![image](https://user-images.githubusercontent.com/20566897/141762542-d9cd8d2f-ec1c-4dbd-862d-dc6a148a1366.png)
似乎在这里有问题， end 没有输出😅（我不太会js，凭感觉瞎改的哈

**Comment by JoysKang** [comment]
你电脑上是不是有 xcode？

**Comment by Allenxuxu** [comment]
> 你电脑上是不是有 xcode？

是的，有 xcode

**Comment by Allenxuxu** [comment]
> ![image](https://user-images.githubusercontent.com/20566897/141762542-d9cd8d2f-ec1c-4dbd-862d-dc6a148a1366.png) 似乎在这里有问题， end 没有输出😅（我不太会js，凭感觉瞎改的哈

有点懵逼，为啥代码到了那个 for 循环里就啥报错没有直接退出了

**Comment by JoysKang** [comment]
获取最新的代码试下

**Comment by Allenxuxu** [comment]
node  src/preload.js 啥输出都没有就返回了

**Comment by JoysKang** [comment]
https://user-images.githubusercontent.com/11786681/141770558-a40bb2fe-e0fb-4a0e-b722-07edf282e7ca.mov

按照这个录屏的方式尝试下看  看看有没有报错信息

**Comment by Allenxuxu** [comment]
Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/xuxu/Library/Application Support/Sublime Text/Local/Session.sublime_session'
    at Object.openSync (fs.js:476)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5)
    at Object.readFileSync (fs.js:377)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5)
    at Object.sublimeParsers (/Users/xx/code/QuickOpen/src/parsers.js:121)
    at getFileContent (/Users/xxx/code/QuickOpen/src/preload.js:79)
    at Object.next (/Users/xx/code/QuickOpen/src/preload.js:114)
    at getHistory (/Users/xxx/code/QuickOpen/src/preload.js:153)
    at async Object.enter (/Users/xxx/code/QuickOpen/src/preload.js:167)

**Comment by JoysKang** [comment]
你原来也没有 Sublime Text 吧

> Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/xuxu/Library/Application Support/Sublime Text/Local/Session.sublime_session' at Object.openSync (fs.js:476) at Object.func [as openSync] (electron/js2c/asar_bundle.js:5) at Object.readFileSync (fs.js:377) at Object.e.readFileSync (electron/js2c/asar_bundle.js:5) at Object.sublimeParsers (/Users/xx/code/QuickOpen/src/parsers.js:121) at getFileContent (/Users/xxx/code/QuickOpen/src/preload.js:79) at Object.next (/Users/xx/code/QuickOpen/src/preload.js:114) at getHistory (/Users/xxx/code/QuickOpen/src/preload.js:153) at async Object.enter (/Users/xxx/code/QuickOpen/src/preload.js:167)

**Comment by Allenxuxu** [comment]
> 你原来也没有 Sublime Text 吧
> 
> > Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/xuxu/Library/Application Support/Sublime Text/Local/Session.sublime_session' at Object.openSync (fs.js:476) at Object.func [as openSync] (electron/js2c/asar_bundle.js:5) at Object.readFileSync (fs.js:377) at Object.e.readFileSync (electron/js2c/asar_bundle.js:5) at Object.sublimeParsers (/Users/xx/code/QuickOpen/src/parsers.js:121) at getFileContent (/Users/xxx/code/QuickOpen/src/preload.js:79) at Object.next (/Users/xx/code/QuickOpen/src/preload.js:114) at getHistory (/Users/xxx/code/QuickOpen/src/preload.js:153) at async Object.enter (/Users/xxx/code/QuickOpen/src/preload.js:167)

是的，我从来没装过

**Comment by JoysKang** [comment]
获取下最新代码试下  做了异常捕获

**Comment by Allenxuxu** [comment]
> 获取下最新代码试下 做了异常捕获

已经可以了

**Comment by JoysKang** [comment]
问一下  删除之后还出现在结果集里面  显示的是"项目路径已不存在" 吗？

**Comment by Allenxuxu** [comment]
> 问一下 删除之后还出现在结果集里面 显示的是"项目路径已不存在" 吗？

我把被我改名的文件，还原了下，没有问题了现在，可以发个版了感觉

**Comment by JoysKang** [comment]
我是问之前的  就是你最开始提这个issue 时的情况
现在的代码如果存在降级  会出现搜索不到的情况

**Comment by JoysKang** [comment]
[Quick Open-1.0.5.upx.zip](https://github.com/JoysKang/QuickOpen/files/7552697/Quick.Open-1.0.5.upx.zip)
使用时间戳去重的版本  可以试下  测测

**Comment by Allenxuxu** [comment]
> 我是问之前的 就是你最开始提这个issue 时的情况 现在的代码如果存在降级 会出现搜索不到的情况

我没明白这个意思

**Comment by Allenxuxu** [comment]
> [Quick Open-1.0.5.upx.zip](https://github.com/JoysKang/QuickOpen/files/7552697/Quick.Open-1.0.5.upx.zip) 使用时间戳去重的版本 可以试下 测测

我直接拉你最新的代码，在本地dev 运行没有问题。

**Comment by JoysKang** [comment]
新版本已发布  关了该 issues
