### ISSUE TITLE
能增加过滤或排序的功能吗

### ISSUE THREAD

**Issue by yingguqing** [JoysKang/QuickOpen#7]
有多个ide，但是常的只有几个，历史记录就会有多个ide的，不方便。
比如我安装了AppCode和xcode，历史记录会同时出现这两个的，但是AppCode我不常用，能否加个功能不显示特定的，或把他们放到最底下。

**Comment by JoysKang** [comment]
最近工作有些忙， 后续会更新上。  加一个配置，设置为 true 时，才启用搜索。

**Comment by JoysKang** [comment]
添加了逻辑：如果IDE历史文件没有标记历史项目最后打开时间，那么采用历史文件的最后访问时间作为排序依据
所以后期不常用的，会排在最后
